[package]
name = "corpus_preview"
version = "0.1.0"
edition = "2021"

[lib]
name = "corpus_preview"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
walkdir = "2"
chardetng = "0.1"
encoding_rs = "0.8"
unicode-segmentation = "1.11"

